// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	ProductID string `json:"productId"`
	UserID    string `json:"userId"`
}

type CreateProductInput struct {
	Name string `json:"name"`
}

type CreateUserInput struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
}

type UpdateProductInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateUserInput struct {
	FullName string `json:"fullName"`
}
